### ISSUE TITLE
When attempting to install in R, package 'hbgd' is not available 

### ISSUE THREAD

**Issue by olyerickson** [hafen/hbgd#1]
Following the suggested procedure for installing 'hbgd'...

```
> options(repos = c(tessera = "http://packages.tessera.io", getOption("repos")))
> install.packages("hbgd")
```

I get...

```
Warning in install.packages :
  package ‘hbgd’ is not available (for R version 3.0.2)
```

**Comment by olyerickson** [comment]
Apologies; I see that >3.1 is required. I've updated my R-base to 3.2.3 and am trying again...

**Comment by olyerickson** [comment]
After tracking down many dependencies and following the devtools-based process, I was successful!

```
devtools::install_github("tesseradata/datadr")
devtools::install_github("tesseradata/trelliscope")
devtools::install_github("bokeh/rbokeh@dev")
devtools::install_github("hafen/hbgd")
```

**Comment by hafen** [comment]
Good!  Sorry for the need to upgrade R - there is a dependency that needs latest R.

**Comment by olyerickson** [comment]
No worries; I try to keep up, but a recent switch to Mint 17.3 64bit somehow made me fall off the pace! ;)

**Comment by a-hendivan** [comment]
after installing it , how do we load it in each session ?
