### ISSUE TITLE
fit_all_trajectories() with 'brokenstick' - 'atknots' and 'atx'

### ISSUE THREAD

**Issue by hdoubleu** [hafen/hbgd#12]
When I call `fit_all_trajectories()` function with a model fitted with _brokenstick_ method, I get the following error:

```
> smc <- get_smocc_data()[1:2000,]
> bstick_fit <- get_fit(smc, y_var = "haz", method = "broken stick")
> all_traj <- fit_all_trajectories(smc, bstick_fit)

*** testing 'fn' on a subset...Error in match.arg(type, c("atknots", "atx")) : 
  'arg' should be one of “atknots”, “ate”
Error: 'fn' ran with errors on a subset:

  Error in match.arg(type, c("atknots", "atx")) : 
  'arg' should be one of “atknots”, “ate”
```

I can replicate this problem on real datasets and also from SMOCC data supplied by _hbgd_ package, when following the documentation for [Modelling Methods](http://hafen.github.io/docs-hbgd/#modeling-methods) section.

I am using the latest _hbgd_ package; I reinstalled the package again.

**Comment by hafen** [comment]
The brokenstick package has been updated and is incompatible with this version of hbgd.  I thought I had merged all my recent updates into master but it looks like I didn't.  I just merged so please reinstall from github and hopefully this will resolve your issue.

**Comment by hdoubleu** [comment]
Thanks for the quick response. I've tested reinstalling `hbgd` from Github on 1 system and it worked. I'll be testing in on another.

**Comment by hdoubleu** [comment]
Tested on 2 systems and the issue has been resolved. Closing this Issue.
