### ISSUE TITLE
How to install "hbgd_labels?"

### ISSUE THREAD

**Issue by olyerickson** [hafen/hbgd#2]
After successfully installing "hbgd," I attempted to install "hbgd_labels" (referred to on the hbgd github as a package https://hafen.github.io/docs-hbgd/index.html ) but it could not be found...

```
> options(repos = c(tessera = "http://packages.tessera.io", getOption("repos")))
> install.packages("hbgd_labels")
Installing package into ‘/home/olyerickson/R/x86_64-pc-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘hbgd_labels’ is not available (for R version 3.2.3)
> 
```

**Comment by hafen** [comment]
`hbgd_labels` isn't another package but a data set that comes with the hbgd package:

"A full list of recognized variable names and associated labels is available in a named list that comes _with_ the package..."

For example, try:

``` s
library(hbgd)
hbgd_labels
```

**Comment by olyerickson** [comment]
Got it...thanks!

```
> hbgd_labels
$agedays
[1] "Age since birth at examination (days)"

$agedth
[1] "Age on day of death (days)"

$animal_fat
[1] "Total Fat (g), Animal source"

$animal_prot
[1] "Total Protein (g), Animal source"
:
:
```

;)
